// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BreadOrderService.proto

package org.example.foodcontainer.breadorderservice;

public interface StreamBreadOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.FoodContainer.StreamBreadOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string OrderRequest = 1;</code>
   */
  java.lang.String getOrderRequest();
  /**
   * <code>string OrderRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderRequestBytes();

  /**
   * <code>string orderTime = 2;</code>
   */
  java.lang.String getOrderTime();
  /**
   * <code>string orderTime = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderTimeBytes();
}
