// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BreadOrderService.proto

package org.example.foodcontainer.proto.breadorderservice;

public interface StreamBreadOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.FoodContainer.StreamBreadOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string OrderResponse = 1;</code>
   */
  java.lang.String getOrderResponse();
  /**
   * <code>string OrderResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderResponseBytes();
}
