// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface FoodStorageServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.FoodStorageServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fruit = 1;</code>
   */
  java.lang.String getFruit();
  /**
   * <code>string fruit = 1;</code>
   */
  com.google.protobuf.ByteString
      getFruitBytes();
}
