// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

/**
 * Protobuf type {@code org.sample.FoodContainer.FoodStorageServiceRequest}
 */
public  final class FoodStorageServiceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.sample.FoodContainer.FoodStorageServiceRequest)
    FoodStorageServiceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FoodStorageServiceRequest.newBuilder() to construct.
  private FoodStorageServiceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FoodStorageServiceRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FoodStorageServiceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.example.foodcontainer.foodstorageservice.Fruit.Builder subBuilder = null;
            if (fruit_ != null) {
              subBuilder = fruit_.toBuilder();
            }
            fruit_ = input.readMessage(org.example.foodcontainer.foodstorageservice.Fruit.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fruit_);
              fruit_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.foodcontainer.foodstorageservice.FoodStorageServiceProto.internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.foodcontainer.foodstorageservice.FoodStorageServiceProto.internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.class, org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.Builder.class);
  }

  public static final int FRUIT_FIELD_NUMBER = 1;
  private org.example.foodcontainer.foodstorageservice.Fruit fruit_;
  /**
   * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
   */
  public boolean hasFruit() {
    return fruit_ != null;
  }
  /**
   * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
   */
  public org.example.foodcontainer.foodstorageservice.Fruit getFruit() {
    return fruit_ == null ? org.example.foodcontainer.foodstorageservice.Fruit.getDefaultInstance() : fruit_;
  }
  /**
   * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
   */
  public org.example.foodcontainer.foodstorageservice.FruitOrBuilder getFruitOrBuilder() {
    return getFruit();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fruit_ != null) {
      output.writeMessage(1, getFruit());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fruit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFruit());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest)) {
      return super.equals(obj);
    }
    org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest other = (org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest) obj;

    boolean result = true;
    result = result && (hasFruit() == other.hasFruit());
    if (hasFruit()) {
      result = result && getFruit()
          .equals(other.getFruit());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFruit()) {
      hash = (37 * hash) + FRUIT_FIELD_NUMBER;
      hash = (53 * hash) + getFruit().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.sample.FoodContainer.FoodStorageServiceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.sample.FoodContainer.FoodStorageServiceRequest)
      org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.foodcontainer.foodstorageservice.FoodStorageServiceProto.internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.foodcontainer.foodstorageservice.FoodStorageServiceProto.internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.class, org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.Builder.class);
    }

    // Construct using org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fruitBuilder_ == null) {
        fruit_ = null;
      } else {
        fruit_ = null;
        fruitBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.foodcontainer.foodstorageservice.FoodStorageServiceProto.internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor;
    }

    @java.lang.Override
    public org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest getDefaultInstanceForType() {
      return org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest build() {
      org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest buildPartial() {
      org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest result = new org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest(this);
      if (fruitBuilder_ == null) {
        result.fruit_ = fruit_;
      } else {
        result.fruit_ = fruitBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest) {
        return mergeFrom((org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest other) {
      if (other == org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest.getDefaultInstance()) return this;
      if (other.hasFruit()) {
        mergeFruit(other.getFruit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.example.foodcontainer.foodstorageservice.Fruit fruit_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.foodcontainer.foodstorageservice.Fruit, org.example.foodcontainer.foodstorageservice.Fruit.Builder, org.example.foodcontainer.foodstorageservice.FruitOrBuilder> fruitBuilder_;
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public boolean hasFruit() {
      return fruitBuilder_ != null || fruit_ != null;
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public org.example.foodcontainer.foodstorageservice.Fruit getFruit() {
      if (fruitBuilder_ == null) {
        return fruit_ == null ? org.example.foodcontainer.foodstorageservice.Fruit.getDefaultInstance() : fruit_;
      } else {
        return fruitBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public Builder setFruit(org.example.foodcontainer.foodstorageservice.Fruit value) {
      if (fruitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fruit_ = value;
        onChanged();
      } else {
        fruitBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public Builder setFruit(
        org.example.foodcontainer.foodstorageservice.Fruit.Builder builderForValue) {
      if (fruitBuilder_ == null) {
        fruit_ = builderForValue.build();
        onChanged();
      } else {
        fruitBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public Builder mergeFruit(org.example.foodcontainer.foodstorageservice.Fruit value) {
      if (fruitBuilder_ == null) {
        if (fruit_ != null) {
          fruit_ =
            org.example.foodcontainer.foodstorageservice.Fruit.newBuilder(fruit_).mergeFrom(value).buildPartial();
        } else {
          fruit_ = value;
        }
        onChanged();
      } else {
        fruitBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public Builder clearFruit() {
      if (fruitBuilder_ == null) {
        fruit_ = null;
        onChanged();
      } else {
        fruit_ = null;
        fruitBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public org.example.foodcontainer.foodstorageservice.Fruit.Builder getFruitBuilder() {
      
      onChanged();
      return getFruitFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    public org.example.foodcontainer.foodstorageservice.FruitOrBuilder getFruitOrBuilder() {
      if (fruitBuilder_ != null) {
        return fruitBuilder_.getMessageOrBuilder();
      } else {
        return fruit_ == null ?
            org.example.foodcontainer.foodstorageservice.Fruit.getDefaultInstance() : fruit_;
      }
    }
    /**
     * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.foodcontainer.foodstorageservice.Fruit, org.example.foodcontainer.foodstorageservice.Fruit.Builder, org.example.foodcontainer.foodstorageservice.FruitOrBuilder> 
        getFruitFieldBuilder() {
      if (fruitBuilder_ == null) {
        fruitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.example.foodcontainer.foodstorageservice.Fruit, org.example.foodcontainer.foodstorageservice.Fruit.Builder, org.example.foodcontainer.foodstorageservice.FruitOrBuilder>(
                getFruit(),
                getParentForChildren(),
                isClean());
        fruit_ = null;
      }
      return fruitBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.sample.FoodContainer.FoodStorageServiceRequest)
  }

  // @@protoc_insertion_point(class_scope:org.sample.FoodContainer.FoodStorageServiceRequest)
  private static final org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest();
  }

  public static org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FoodStorageServiceRequest>
      PARSER = new com.google.protobuf.AbstractParser<FoodStorageServiceRequest>() {
    @java.lang.Override
    public FoodStorageServiceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FoodStorageServiceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FoodStorageServiceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FoodStorageServiceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.foodcontainer.foodstorageservice.FoodStorageServiceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

