// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface FoodStorageServiceResponseManyTimesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.FoodStorageServiceResponseManyTimes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
