// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public final class FoodStorageServiceProto {
  private FoodStorageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_Fruit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_Fruit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030FoodStorageService.proto\022\030org.sample.F" +
      "oodContainer\"<\n\005Fruit\022\021\n\tfruitCode\030\001 \001(\t" +
      "\022\021\n\tfruitType\030\002 \001(\t\022\r\n\005fruit\030\003 \001(\t\"P\n\031Fo" +
      "odStorageServiceRequest\022\r\n\005fruit\030\001 \001(\t\022\021" +
      "\n\tfruitCode\030\002 \001(\t\022\021\n\tfruitType\030\003 \001(\t\",\n\032" +
      "FoodStorageServiceResponse\022\016\n\006result\030\001 \001" +
      "(\t\"7\n!StreamFoodEmptySpaceUpdateRequest\022" +
      "\022\n\nspaceQuery\030\001 \001(\t\"9\n\"StreamFoodEmptySp" +
      "aceUpdateResponse\022\023\n\013spaceUpdate\030\001 \001(\t2\262" +
      "\002\n\022FoodStorageService\022y\n\014fruitStorage\0223." +
      "org.sample.FoodContainer.FoodStorageServ" +
      "iceRequest\0324.org.sample.FoodContainer.Fo" +
      "odStorageServiceResponse\022\240\001\n!streamFoodE" +
      "mptySpaceUpdateRequest\022;.org.sample.Food" +
      "Container.StreamFoodEmptySpaceUpdateRequ" +
      "est\032<.org.sample.FoodContainer.StreamFoo" +
      "dEmptySpaceUpdateResponse0\001BI\n,org.examp" +
      "le.foodcontainer.foodstorageserviceB\027Foo" +
      "dStorageServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_sample_FoodContainer_Fruit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_sample_FoodContainer_Fruit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_Fruit_descriptor,
        new java.lang.String[] { "FruitCode", "FruitType", "Fruit", });
    internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor,
        new java.lang.String[] { "Fruit", "FruitCode", "FruitType", });
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateRequest_descriptor,
        new java.lang.String[] { "SpaceQuery", });
    internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_StreamFoodEmptySpaceUpdateResponse_descriptor,
        new java.lang.String[] { "SpaceUpdate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
