// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface FoodStorageServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.FoodStorageServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
   */
  boolean hasFruit();
  /**
   * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
   */
  org.example.foodcontainer.foodstorageservice.Fruit getFruit();
  /**
   * <code>.org.sample.FoodContainer.Fruit fruit = 1;</code>
   */
  org.example.foodcontainer.foodstorageservice.FruitOrBuilder getFruitOrBuilder();
}
