// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public final class FoodStorageServiceProto {
  private FoodStorageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_Fruit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_Fruit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponseManyTimes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sample_FoodContainer_FoodStorageServiceResponseManyTimes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030FoodStorageService.proto\022\030org.sample.F" +
      "oodContainer\",\n\005Fruit\022\024\n\014fruit_number\030\001 " +
      "\001(\t\022\r\n\005fruit\030\002 \001(\t\"K\n\031FoodStorageService" +
      "Request\022.\n\005fruit\030\001 \001(\0132\037.org.sample.Food" +
      "Container.Fruit\",\n\032FoodStorageServiceRes" +
      "ponse\022\016\n\006result\030\001 \001(\t\"5\n#FoodStorageServ" +
      "iceResponseManyTimes\022\016\n\006result\030\001 \001(\t2\237\002\n" +
      "\022FoodStorageService\022y\n\014FruitStorage\0223.or" +
      "g.sample.FoodContainer.FoodStorageServic" +
      "eRequest\0324.org.sample.FoodContainer.Food" +
      "StorageServiceResponse\022\215\001\n\025FruitStorageM" +
      "anyTimes\0223.org.sample.FoodContainer.Food" +
      "StorageServiceRequest\032=.org.sample.FoodC" +
      "ontainer.FoodStorageServiceResponseManyT" +
      "imes0\001BI\n,org.example.foodcontainer.food" +
      "storageserviceB\027FoodStorageServiceProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_sample_FoodContainer_Fruit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_sample_FoodContainer_Fruit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_Fruit_descriptor,
        new java.lang.String[] { "FruitNumber", "Fruit", });
    internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_FoodStorageServiceRequest_descriptor,
        new java.lang.String[] { "Fruit", });
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_FoodStorageServiceResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponseManyTimes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_sample_FoodContainer_FoodStorageServiceResponseManyTimes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sample_FoodContainer_FoodStorageServiceResponseManyTimes_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
