// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface FruitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.Fruit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fruitCode = 1;</code>
   */
  java.lang.String getFruitCode();
  /**
   * <code>string fruitCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getFruitCodeBytes();

  /**
   * <code>string fruitType = 2;</code>
   */
  java.lang.String getFruitType();
  /**
   * <code>string fruitType = 2;</code>
   */
  com.google.protobuf.ByteString
      getFruitTypeBytes();

  /**
   * <code>string fruit = 3;</code>
   */
  java.lang.String getFruit();
  /**
   * <code>string fruit = 3;</code>
   */
  com.google.protobuf.ByteString
      getFruitBytes();
}
