// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface FruitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.Fruit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fruit_number = 1;</code>
   */
  java.lang.String getFruitNumber();
  /**
   * <code>string fruit_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getFruitNumberBytes();

  /**
   * <code>string fruit = 2;</code>
   */
  java.lang.String getFruit();
  /**
   * <code>string fruit = 2;</code>
   */
  com.google.protobuf.ByteString
      getFruitBytes();
}
