// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface StreamClientFruitTypeOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.StreamClientFruitTypeOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result2 = 1;</code>
   */
  java.lang.String getResult2();
  /**
   * <code>string result2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getResult2Bytes();
}
