// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface StreamClientFruitTypeOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.FoodContainer.StreamClientFruitTypeOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fruitType = 1;</code>
   */
  java.lang.String getFruitType();
  /**
   * <code>string fruitType = 1;</code>
   */
  com.google.protobuf.ByteString
      getFruitTypeBytes();
}
