// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface StreamFoodEmptySpaceUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.FoodContainer.StreamFoodEmptySpaceUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string spaceQuery = 1;</code>
   */
  java.lang.String getSpaceQuery();
  /**
   * <code>string spaceQuery = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpaceQueryBytes();
}
