// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodStorageService.proto

package org.example.foodcontainer.foodstorageservice;

public interface StreamFoodEmptySpaceUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sample.FoodContainer.StreamFoodEmptySpaceUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string spaceUpdate = 1;</code>
   */
  java.lang.String getSpaceUpdate();
  /**
   * <code>string spaceUpdate = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpaceUpdateBytes();
}
