// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FruitCodeScanService.proto

package org.example.foodcontainer.fruitcodescanservice;

public interface FruitCodeScanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.FoodContainer.FruitCodeScanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scanResponse = 1;</code>
   */
  java.lang.String getScanResponse();
  /**
   * <code>string scanResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getScanResponseBytes();
}
