// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FruitCodeScanService.proto

package org.example.foodcontainer.fruitcodescanservice;

public interface StreamFruitCodeScanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.FoodContainer.StreamFruitCodeScanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scanRequest = 1;</code>
   */
  java.lang.String getScanRequest();
  /**
   * <code>string scanRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getScanRequestBytes();

  /**
   * <code>string scanTime = 2;</code>
   */
  java.lang.String getScanTime();
  /**
   * <code>string scanTime = 2;</code>
   */
  com.google.protobuf.ByteString
      getScanTimeBytes();
}
